#!/bin/bash

ID=$( echo '{"command":"list_devices"}' | ncat -U /run/lactd.sock | cut -d , -f 2 | cut -d \" -f 6 )

# This function should build out a $CMD to be evaluated and sent to the socket
# $command $arg1 $val1 $arg2 $val2 $arg3 $val3
# eg... 
# lactd system_info
# lactd get_power_states id $ID
# lactd confirm_pending_config command confirm
# lactd set_power_profile_mode id $ID index 0
# lactd confirm_pending_config command confirm
# lactd set_profile name null auto_switch false

lactd(){
CMD='{"command":"'"$1"'"'
shift

if [ $# -ne 0 ] ;then
    CMD=$CMD',"args":{'
fi

while (( "$#" )); do
case "$2" in
    [0-9] | null | false | true)
        CMD="$CMD"'"'"$1"'":'"$2"
    ;;
    *)
        CMD="$CMD"'"'"$1"'":"'"$2"'"'
    ;;
esac
    shift 2
        if [ $# -ne 0 ] ;then
            CMD=$CMD','
        else
            CMD=$CMD'}'
        fi
done
CMD=$CMD'}'
#echo "$CMD"
eval echo '"$CMD"' | ncat -U /run/lactd.sock
}

# Below are explicit functions
_ping() {
echo '{"command":"ping"}' | ncat -U /run/lactd.sock
}

_list_devices() {
echo '{"command":"list_devices"}' | ncat -U /run/lactd.sock
}

_system_info() {
echo '{"command":"system_info"}' | ncat -U /run/lactd.sock
}

_device_info() {
echo '{"command":"device_info","args":{"id":"'"$ID"'"}}' | ncat -U /run/lactd.sock
}

_device_stats() {
echo '{"command":"device_stats","args":{"id":"'"$ID"'"}}' | ncat -U /run/lactd.sock
}

_device_clocks_info() {
echo '{"command":"device_clocks_info","args":{"id":"'"$ID"'"}}' | ncat -U /run/lactd.sock
}

_device_power_profile_modes() {
echo '{"command":"device_power_profile_modes","args":{"id":"'"$ID"'"}}' | ncat -U /run/lactd.sock
}

#set_fan_control() {
#
#}

#reset_pmfw() {
#
#}

set_power_cap() {
echo '{"command":"set_power_cap","args":{"id":"'"$ID"'","cap":'"$1"'}}' | ncat -U /run/lactd.sock
confirm_pending_config
}

set_performance_level() {
    case "$1" in
    auto | low | high)
        echo '{"command":"set_performance_level","args":{"id":"'"$ID"'","performance_level":"manual"}}' | ncat -U /run/lactd.sock
        confirm_pending_config
        echo '{"command":"set_power_profile_mode","args":{"id":"'"$ID"'","index":null}}' | ncat -U /run/lactd.sock
        confirm_pending_config
        echo '{"command":"set_performance_level","args":{"id":"'"$ID"'","performance_level":"'"$1"'"}}' | ncat -U /run/lactd.sock
        confirm_pending_config
        ;;
    *)
        echo "You need to specify a performance level low | high auto"
        ;;
    esac
}

#set_clocks_value() {
#
#}

#batch_set_clocks_value() {
#
#}

set_power_profile_mode() {
    case "$1" in
    [0-6])
        echo '{"command":"set_performance_level","args":{"id":"'"$ID"'","performance_level":"manual"}}' | ncat -U /run/lactd.sock
        confirm_pending_config
        echo '{"command":"set_power_profile_mode","args":{"id":"'"$ID"'","index":'$1'}}' | ncat -U /run/lactd.sock
        confirm_pending_config
        ;;
    auto)
        echo '{"command":"set_performance_level","args":{"id":"'"$ID"'","performance_level":"manual"}}' | ncat -U /run/lactd.sock
        confirm_pending_config
        echo '{"command":"set_power_profile_mode", "args":{"id":"'"$ID"'","index":null}}' | ncat -U /run/lactd.sock
        confirm_pending_config
        echo '{"command":"set_performance_level","args":{"id":"'"$ID"'","performance_level":"auto"}}' | ncat -U /run/lactd.sock
        confirm_pending_config
        ;;
    *)
        echo "You need to specify a power profile [0-6] | auto"
        ;;
    esac
}

_get_power_states() {
echo '{"command":"get_power_states", "args":{"id":"'"$ID"'"}}' | ncat -U /run/lactd.sock
}

#set_enabled_power_states
#vbios_dump

_list_profiles() {
echo '{"command":"list_profiles","args":{"id":"'"$ID"'"}}' | ncat -U /run/lactd.sock
}

#_list_profiles_short() {
#echo '{"command":"list_profiles","args":{"include_state":false}}' | ncat -U /run/lactd.sock
#}

set_profile() {
echo '{"command":"set_profile","args":{"name":"'"$1"'","auto_switch":false}}' | ncat -U /run/lactd.sock
}

set_profile_null() {
echo '{"command":"set_profile","args":{"name":null,"auto_switch":false}}' | ncat -U /run/lactd.sock
}

create_profile() {
echo '{"command":"create_profile","args":{"name":"'"$1"'","base":"default"}}' | ncat -U /run/lactd.sock
}

create_profile_empty() {
echo '{"command":"create_profile","args":{"name":"'"$1"'","base":"empty"}}' | ncat -U /run/lactd.sock
}

delete_profile() {
echo '{"command":"delete_profile","args":{"name":"'"$1"'"}}' | ncat -U /run/lactd.sock
}

move_profile() {
# position in the profile list, numbering starts at 0 being the first position
echo '{"command":"move_profile","args":{"name":"'"$1"'","new_position":'"$2"'}' | ncat -U /run/lactd.sock
}

#evaluate_profile_rule() {
#
#}

#set_profile_rule() {
#
#}

#enable_overdrive() {
#
#}

#disable_overdrive() {
#
#}

#generate_snapshot() {
#
#}

confirm_pending_config() {
    echo '{"command":"confirm_pending_config","args":{"command":"confirm"}}' | ncat -U /run/lactd.sock
}

lactd system_info
